### PR TITLE
Add Win32_LOB_App.ps1 sample file

### PR DESCRIPTION
**Pull request by Daigle-ISM**
Add a sample file for uploading a Win32_LOB application using MSAL, similar to `iOS_Application_LOB_App.ps1` and the old `microsoftgraph/powershell-intune-samples/blob/master/LOB_Application/Win32_Application_Add.ps1`

File includes comment help blocks with examples

### CODE REVIEW

**Comment by Daigle-ISM** [comment]
@microsoft-github-policy-service agree company="ISM"

**Comment by Mahopper** [comment]
Thanks for the contribution @Daigle-ISM. Timing is interesting on this one- I just finished the updated sample and documentation which contains a handful of reworks on Win32_Application_Add.ps1 here: https://github.com/microsoft/mggraph-intune-samples/pull/17

We'll take a look at the sample you provided, and see if we can merge any of your changes/methods to the script in https://github.com/microsoft/mggraph-intune-samples/pull/17. Thanks again.

**Comment by Daigle-ISM** [comment]
> Thanks for the contribution @Daigle-ISM. Timing is interesting on this one- I just finished the updated sample and documentation which contains a handful of reworks on Win32_Application_Add.ps1 here: #17
> 
> We'll take a look at the sample you provided, and see if we can merge any of your changes/methods to the script in #17. Thanks again.

Oh that's a bit unfortunate, but I appreciate your work on this. I would be surprised if there was anything in my sample that you haven't already covered (besides some style choices and small things like `#requires` instead of `import-module`), let me know if you have questions/need anything

**Comment by Mahopper** [comment]
@Daigle-ISM Sure thing- I've added your suggestion to use #requires instead of import-module. Going to close this out for now- thanks again for the submission.

**Pull request closed without merging**
